sudo: false
language: ruby
dist: trusty
cache:
  directories:
    - travis_phantomjs
before_install:
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
rvm:
  - 2.3.1
env:
  matrix:
    - SOLIDUS_BRANCH=v1.2
    - SOLIDUS_BRANCH=v1.3
    - SOLIDUS_BRANCH=v1.4
    - SOLIDUS_BRANCH=v2.0
    - SOLIDUS_BRANCH=master
